### PR TITLE
Generic Layout for Configuration Panel is added for Server UI

### PR DESCRIPTION
**Pull request by sangeetha151294**
1. Expression Panel Compounds are added

### CODE REVIEW

**Review by varun1309 — COMMENTED** [review]
1. Try to use the already defined model of Message when setting its field in ServerCommonData.
2. Also, try to give relevant names to splitPane objects.
3. Optionally, since this new method is very big, can we split it into other methods to keep max LOC 100? thanks

**Review by varun1309 — APPROVED** [review]

**Comment by varun1309** [comment]
Guys approve this PR, it has many important commits for client-server integration.

**Comment by mtandon3** [comment]
Agreed with Varun with above points.
Also please refrain from using keywords that are difficult to understand.Also using shortforms and abbreviations.
Eg. eyeAct it can be changes to eyeStatus

**Review by mtandon3 — CHANGES_REQUESTED** [review]
Variable names that can be changed:
lowerFaceLbl, lowerFaceGbc, lowerFaceComboGbc, exprPanel, lowerFaceAct, lowerFaceActGbc, upperFaceLbl, upperFaceGbc, upperFaceComboGbc, upperFaceAct, splitPane1, splitPane2, splitPane3.. There are more.Please review.

**Review by mtandon3 — APPROVED** [review]

**Pull request merged**
